version: "3.8"
services:
 postgres:
   image: postgres:latest
   container_name: postgres_db
   restart: always
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: Quantum9963
     POSTGRES_DB: QUANTUM
   volumes:
     - postgres-data:/var/lib/postgresql/data
 app:
   build: .
   container_name: myapplication
   depends_on:
     - postgres
   environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/QUANTUM
     SPRING_DATASOURCE_USERNAME: postgres
     SPRING_DATASOURCE_PASSWORD: Quantum9963
   ports:
     - "8084:8084"
volumes:
 postgres-data:
